
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(ggridges)
library(lubridate)
library(ggmap)
library(httr)
library(cowplot)
library(janitor)
library(repmis)
library(readxl)
library(rlist)
library(RCurl)
library(ggrepel)
library(here)
```


```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
#load master data_frame
data_fish <- readRDS(url("https://github.com/JMRidgway/Freshwater-Fish-Diet-Database/blob/master/database/data_fish.rds?raw=true")) %>% 
  mutate_all(funs('as.character')) %>% 
  remove_empty("rows")

#load all diversity of fishes
fishbase_div <- read_csv("https://raw.githubusercontent.com/jswesner/fish_summaries/master/family_diversity.csv") %>% 
  mutate(prop_species_fb = no_fish_species/sum(no_fish_species),
         data = "fishbase") %>% 
  rename(no_fish_species_fb = no_fish_species)

fams_in_db <- data_fish %>% 
  distinct(fish_species, fish_family) %>% 
  group_by(fish_family) %>% 
  tally() %>% 
  arrange(-n) %>% 
  ungroup() %>% 
  mutate(prop_species = n/sum(n),
         data = "in database") %>% 
  rename(no_fish_species_db = n,
         prop_species_db = prop_species,
         Family = fish_family)

all <- fishbase_div  %>% select(Family, no_fish_species_fb, prop_species_fb) %>% 
  # filter(no_fish_species >= 100) %>% 
  left_join(fams_in_db %>% select(Family, no_fish_species_db, prop_species_db))  %>% 
  filter(!is.na(Family)) %>% 
  gather(group, prop_species, c(prop_species_fb, prop_species_db)) %>% 
  gather(group_no, no_fish_species, c(no_fish_species_fb, no_fish_species_db)) %>% 
  mutate(database = case_when(grepl("fb", group) ~ "FishBase",TRUE ~ "Our database"),
         sort = case_when(grepl("fb", group) ~ prop_species,TRUE ~ 0),
         split = case_when(sort >= 0.001 ~ "common",
                           sort >= 0.0001 ~ "rare",
                           sort >= 0.00001 ~ "rarest"))


family_diversity_plot <- all %>% 
  filter(group_no == "no_fish_species_fb") %>%
  # filter(prop_species >=0.001) %>% 
  ggplot(aes(x = reorder(Family,sort), y = prop_species, group = database, 
             color = database,
             fill = database,
             alpha = database)) +
  # geom_point() +
  geom_bar(stat = "identity", position = position_dodge(width = 0)) +
  coord_flip() +
  scale_alpha_manual(values = c(1, 0.4)) +
  # facet_wrap(~split) +
  theme(axis.text.y = element_text(size = 2.5)) +
  labs(x = "Fish Family",
       y = "Proportion of species in the family")

family_diversity_plot
ggsave(family_diversity_plot, file = here("plots/family_diversity_plot.jpg"), width = 7, height = 9, units = "in", dpi = 500)
```

```{r}
# overrepresented families

differences <- all %>% 
  filter(group_no == "no_fish_species_fb") %>% 
  select(Family, database, prop_species) %>% 
  pivot_wider(names_from = database, values_from = prop_species) %>% 
  mutate(difference = `Our database` - FishBase) 

differences %>% 
  arrange(-difference) %>%
  filter(!is.na(difference)) %>% 
  filter(difference >= 0.005) %>% 
  ggplot(aes(x = reorder(Family, difference), y = difference)) + 
  geom_point() +
  geom_hline(yintercept = 0) +
  labs(y = "Overrepresentation (Proportion in Database minus proportion in FishBase)", 
       x = "Fish Family") +
  coord_flip()

```

