library(tidyverse)
library(janitor)

#full database
data_fish <- readRDS(url("https://github.com/JMRidgway/Freshwater-Fish-Diet-Database/blob/master/database/data_fish.rds?raw=true")) %>% 
  mutate_all(funs('as.character')) %>% 
  remove_empty("rows")

data_fish %>% 
  mutate(prey_order = case_when(prey_order %in% c("Anisoptera", "Zygoptera") ~ "Odonata",
                                TRUE ~ prey_order)) %>% 
  filter(prey_class == 'Insecta') %>% 
  distinct(prey_order)

temp <- data_fish %>% 
  filter(prey_taxon != "spp.",
         prey_taxon != "spp",
         prey_taxon != "vetullus") %>% 
  mutate(prey_class = case_when(prey_class == "Actinopteri" ~ "Actinopterygii",
                                prey_class == "Amphibian" ~ "Amphibia",
                                prey_class == "Arachnidae" ~ "Arachnida",
                                prey_class == "Branchipoda" ~ "Branchiopoda",
                                prey_family == "Microcystaceae" ~ "Cyanophyceae",
                                prey_class == "Zygnemophyceae" ~ "Zygnematophyceae",
                                prey_taxon %in% c("flagellates","helminth") ~ "unknown",
                                prey_taxon == "hydroids" ~ "Hydrozoa",
                                grepl("crab", prey_taxon) ~ "Malacostraca",
                                prey_taxon == "opossum shrimp" ~ "Malacostraca",
                                prey_taxon == "dugesia_sp" ~ "Rhabditophora",
                                prey_taxon == "Calanoida" ~ "Hexanauplia",
                                prey_taxon %in% c("Ictalurus", "Unknown Fish") ~ "Actinopterygii",
                                prey_taxon == "brachionus_angularis" ~ "Monogononta",
                                prey_taxon == "prawn" ~ "Malacostraca",
                                prey_taxon %in% c("Ictalurus", "Noturusflavus") ~ "Actinopterygii",
                                prey_taxon == "lymneidae" ~ "Gastropoda",
                                prey_family == "Crustaceae" ~ "unknown",
                                prey_family == "hydracnellae" ~ "Arachnida",
                                prey_taxon == "Leptoceridae" ~ "Insecta",
                                prey_family == "Orchestiidae" ~ "Malacostraca",
                                prey_taxon == "neritidae" ~ "Gastropoda",
                                prey_taxon == "	bythinidae" ~ "Gastropoda",
                                prey_taxon == "daphnids" ~ "Branchiopoda",
                                TRUE ~ prey_class),
         prey_kingdom = case_when(prey_family == "Microcystaceae" ~ "Bacteria",
                                  prey_taxon %in% c("Unknown Fish", "helminth", "Calanoida", "dugesia_sp",
                                                    "Leptoceridae") ~ "Animalia",
                                  prey_taxon == "flagellates" ~ "Plantae",
                                  prey_family == "Crustaceae" ~ "Animalia",
                                  TRUE ~ prey_kingdom),
         prey_order = case_when(prey_order %in% c("Anisoptera", "Zygoptera") ~ "Odonata",
                                prey_family %in% c("Ameletidae", "Baetidae","Ephemeridae") ~ "Ephemeroptera",
                                grepl("crab", prey_taxon) ~ "Decapoda",
                                prey_taxon %in% c("helminth", "flagellates", "hydroids","Unknown Fish") ~ "unknown",
                                prey_taxon == "opossum shrimp" ~ "Mysida",
                                prey_taxon == "dugesia_sp" ~ "Tricladida",
                                prey_taxon %in% c("Hydropsyche", "Hydropsychidae","Leptoceridae", 
                                                  "Polycentropodidae") ~ "Trichoptera",
                                prey_taxon == "Calanoida" ~ "Calnoida",
                                prey_taxon == "brachionus_angularis" ~ "Plioma",
                                prey_taxon == "prawn" ~ "Decapoda",
                                prey_taxon == "Nigronia" ~ "Megaloptera",
                                prey_taxon %in% c("Ictalurus", "Noturusflavus") ~ "Siluriformes",
                                prey_taxon == "lymneidae" ~ "unknown",
                                prey_family %in% c("Libellulidae", "Coenogrionidae") ~ "Odonata",
                                prey_family == "Corizidae" ~ "Hemiptera",
                                prey_family == "Corydalidae" ~ "Megaloptera",
                                prey_family == "Crustaceae" ~ "unknown",
                                prey_family == "Gerridae" ~ "Hemiptera",
                                prey_family == "Gomphidae" ~ "Odonata",
                                prey_family %in% c("Limnephilidae","Limnephelidae") ~ "Trichoptera",
                                prey_taxon == "Ametropus" ~ "Ephemeroptera",
                                prey_family == "Notodontidae" ~ "Lepidoptera",
                                prey_family == "Orchestiidae" ~ "Amphipoda",
                                prey_taxon == "grasshopper legs" ~ "Orthoptera",
                                prey_family == "Perlidae" ~ "Plecoptera",
                                prey_taxon == "neritidae" ~ "Cycloneritida",
                                prey_taxon == "bythinidae" ~ "Littorinimorpha",
                                prey_taxon == "daphnids" ~ "Cladocera", 
                                TRUE ~ prey_order),
         prey_phylum = case_when(prey_phylum == "Ocrophyta" ~ "Ochrophyta",
                                 grepl("crab", prey_taxon) ~ "Arthropoda",
                                 prey_taxon == "helminth" ~ "Platyhelminthes",
                                 prey_taxon %in% c("Leptocerida", "opossum shrimp") ~ "Arthropoda",
                                 prey_taxon == "dugesia_sp" ~ "Platyhelminthes",
                                 prey_taxon == "flagellates" ~ "Chlorophyta",
                                 prey_taxon == "brachionus_angularis" ~ "Rotifera",
                                 prey_taxon %in% c("Ictalurus", "Noturusflavus") ~ "Chordata",
                                 prey_taxon == "lymneidae" ~ "Mollusca",
                                 prey_taxon %in% c("bythinidae", "neritidae") ~ "Mollusca",
                                 prey_family %in% c("Orchestiidae", "Crustaceae") ~ "Arthropoda",
                                 TRUE ~ prey_phylum),
         prey_subphylum = case_when(grepl("crab", prey_taxon) ~ "Crustacea",
                                    prey_taxon == "opossum shrimp" ~ "Crustacea",
                                    prey_family == "Crustaceae" ~ "Crustacea",
                                    prey_taxon == "daphnids" ~ "Crustacea",
                                    TRUE ~ prey_subphylum),
         prey_superclass = case_when(grepl("Oste", prey_superclass) ~ "Osteichthyes",
                                     TRUE ~ prey_superclass),
         prey_order = case_when(prey_taxon %in% c("other", "Other",
                                                  "other 32", "other 38", "flagellates") ~ "unknown",
                                prey_class == "Calanoida" ~ "Calanoida",
                                TRUE ~ prey_order),
         prey_family = case_when(prey_taxon %in% c("other", "Other",
                                                  "other 32", "other 38", "flagellates") ~ "unknown",
                                 prey_family == "Bulindae" ~ "Bulinidae",
                                 prey_family == "Colubridae" ~ "unknown",
                                 prey_taxon == "helminth" ~ "unknown",
                                 prey_taxon == "hydroids" ~ "unknown",
                                 prey_taxon == "opossum shrimp" ~ "unknown",
                                 prey_taxon == "dugesia_sp" ~ "Dugesiidae",
                                 prey_taxon == "Hydropsychidae" ~ "Hydropsychidae",
                                 prey_taxon %in% c("Unknown Fish", "Calanoida", "prawn", "hydrachnellae",
                                                   "organic_mat_undet", "organic_matter", 
                                                   "organic_matter_not_identified", "grasshopper legs") ~ "unknown",
                                 prey_taxon == "helodidae" ~ "Helodidae",
                                 prey_taxon == "brachionus_angularis" ~ "Brachionidae",
                                 prey_taxon == "Nigronia" ~ "Corydalidae",
                                 prey_taxon %in% c("Ictalurus", "Noturusflavus") ~ "Ictaluridae",
                                 prey_taxon == "lymneidae" ~ "Lymnaeidae",
                                 prey_family == "Ceratoponidae" ~ "Ceratopogonidae",
                                 prey_family == "Crustaceae" ~ "unknown",
                                 prey_family == "Curculionidae" ~ "Circulionidae",
                                 prey_taxon == "Ametropus" ~ "Ametropodidae",
                                 prey_taxon == "neritidae" ~ "Neritidae",
                                 prey_taxon == "bythinidae" ~ "Bythiniidae",
                                 prey_taxon %in% c("tipula sp_larvae", "tipula") ~ "Tipulidae",
                                 prey_taxon == "daphnids" ~ "Daphniidae",
                                TRUE ~ prey_family),
         prey_species = case_when(prey_taxon %in% c("other", "Other",
                                                  "other 32", "other 38") ~ "unknown",
                                  prey_taxon == "dugesia_sp" ~ "Dugesia sp.",
                                  prey_taxon == "brachionus_angularis" ~ "Brachionus angularis",
                                  prey_taxon == "Nigronia" ~ "Nigronia sp.",
                                  prey_taxon == "Noturusflavus" ~ "Noturus flavus",
                                  prey_taxon == "Hydropsyche" ~ "Hydropsyche sp.",
                                  prey_taxon == "Ametropus" ~ "Ametropus sp.",
                                  prey_taxon == "naucoris" ~ "naucoris sp.",
                                  prey_taxon == "anisops" ~ "Anisops sp.",
                                  prey_taxon == "Ictalurus" ~ "Ictalurus sp.",
                                  prey_taxon == "daphnids" ~ "Daphnia sp.",
                                  prey_taxon == "stenotrachelus sp" ~ "Senotrachelus sp.",
                                TRUE ~ prey_species),
         prey_class = case_when(prey_taxon %in% c("other", "Other",
                                                  "other 32", "other 38") ~ "unknown",
                                TRUE ~ prey_class),
         prey_subclass = case_when(prey_taxon %in% c("other", "Other",
                                                  "other 32", "other 38") ~ "unknown",
                                   prey_taxon == "hydracnellae" ~ "Acari",
                                TRUE ~ prey_subclass),
         prey_superclass = case_when(prey_taxon %in% c("other", "Other",
                                                  "other 32", "other 38") ~ "unknown",
                                TRUE ~ prey_superclass),
         prey_subphylum = case_when(prey_taxon %in% c("other", "Other",
                                                  "other 32", "other 38") ~ "unknown",
                                TRUE ~ prey_subphylum),
         prey_kingdom = case_when(prey_taxon %in% c("other", "Other",
                                                      "other 32", "other 38") ~ "unknown",
                                    TRUE ~ prey_kingdom),
         prey_phylum = case_when(prey_taxon %in% c("other", "Other",
                                                      "other 32", "other 38") ~ "unknown",
                                    TRUE ~ prey_phylum)) %>% 
  mutate(prey_origin = case_when(prey_order %in% c("Trichoptera", "Arcellinida",
                                                   "Ephemeroptera", "Alismatales",
                                                   "Plecoptera",
                                                   "Megaloptera",
                                                   "Odonata",
                                                   "Physida",
                                                   "Pleurotomariida",
                                                   "Calanoida", "Oscillatoriales",
                                                   "Hirudinea","Littorinimorpha",
                                                   "Ctenostomatida", "Perciformes") ~ "aquatic",
                                 prey_class %in% c("Bacillariophyceae", "Actinopterygii",
                                                   "Bivalvia", "Branchiopoda", "Monogononta",
                                                   "Bryopsida", "Oligohymenophorea",
                                                   "Dinophyceae",
                                                   "Amphibia", "Rhynchonellata",
                                                   "Chlorophyceae",
                                                   "Branchiopoda",
                                                   "Cephalopoda", "Ulvophyceae",
                                                   "Chrysophyceae", "Hexanauplia",
                                                   "Cyanophyceae","Euglenophyceae", "Echinoidea",
                                                   "Eurotatoria","Florideophyceae", "Teleostei",
                                                   "Ostracoda", "Malacostraca", "Zygnematophyceae") ~ "aquatic",
                                 prey_superclass == "Osteichthyes" ~ "aquatic",
                                 prey_subclass %in% c("Acari", "Hirudinea", "Copepoda") ~ "aquatic",
                                 prey_subphylum %in% c("Crustacea") ~ "aquatic",
                                 prey_kingdom %in% c("Chromista") ~ "aquatic",
                                 prey_family %in% c("Naididae", 'Araceae', "Nereididae", "Dugesiidae",
                                                    "Valvatidae", "Tendipedidae", "Corixidae",
                                                    "Tubificidae", "Chironomidae", "Simuliidae",
                                                    "Lumbriculidae", "Argulidae", "Chaoboridae",
                                                    "Culicidae", "Dolichopodidae", "Ephydridae",
                                                    "Spongillidae","Lymnaeidae","Physidae",
                                                    "Planorbidae","Viviparidae", "Thiaridae",
                                                    "Paludomidae", "Pleuroceridae", "Bulinidae", "Ampullariidae",
                                                    "Diastomatidae", "Empididae", "Limoniidae",
                                                    "Tabanidae", "Hydraenidae", "Dixidae", "Aeshnidae",
                                                    "Hydrocharitaceae", "Athericidae", "Hydrophilidae",
                                                    "Helodidae", "Dytiscidae", "Gyrinidae", "Haliplidae",
                                                    "Psephenidae", "Dryopidae", "Belostomatidae", "Blephariceridae",
                                                    "Ceratopogonidae", "Gerridae", "Hebridae", "Pleidae",
                                                    "Heleidae", "Mesoveliidae", "Naucoridae", "Noteridae",
                                                    "Notonectidae", "Scirtidae", "Sisyridae", "Veliidae") ~ "aquatic",
                                 prey_phylum %in% c("Charophyta",
                                                   "Chlorophyta",
                                                   "Ochrophyta",
                                                   "Rotifera",
                                                   "Cyanobacteria",
                                                   "Euglenophyta",
                                                   "Euglenozoa",
                                                   "Rhodophyta",
                                                   "Foraminifera",
                                                   "Rotifera", "Tardigrada") ~ "aquatic",
                                 prey_order %in% c("Orthoptera",
                                                   "Psocoptera",
                                                   "Blattodea",
                                                   "Thysanoptera",
                                                   "Stylommatophora",
                                                   "Araneae",
                                                   "Opisthopora",
                                                   "Poales", "Orthoptera") ~ "terrestrial",
                                 prey_class %in% c("Chilopoda",
                                                   	"Diplopoda", "Magnoliopsida",
                                                   "Lichinomycetes","Lecanoromycetes") ~ "terrestrial",
                                 prey_family %in% c("Lumbricidae", "Aciculidae","Eucnemidae","Carabidae",
                                                    "Cosmopterigidae", "Canacidae", "Andrenidae",
                                                    "Anisopodidae", "Anthomyiidae", "Aphididae",
                                                    "Aphodiidae", "Apidae", "Colubridae",
                                                    "Asilidae", "Asparagaceae", "Aulacidae",
                                                    "Helmidae", "Melolonthidae", "Scarabaeidae",
                                                    "Elateridae", "Tenebrionidae", "Coccinellidae",
                                                    "Buprestidae", "Cerambycidae", "Cercopidae", "Piophilidae",
                                                    "Chrysomelidae", "Cicadellidae", "Cicadidae", "Corizidae",
                                                    "Crabronidae", "Crambidae", "Cupesidae", "Phoridae",
                                                    "Circulionidae", "Curtonotidae", "Delphacidae",
                                                    "Dermestidae", "Drosophilidae", "Dryomyzidae",
                                                    "Formicidae", "Heleomyzidae", "Helophoridae", "Pentatomidae",
                                                    "Heteroceridae", "Ichneumonidae","Lampyridae", "Pediciidae",
                                                    "Lauxaniidae","Lygaeidae", "Miridae","Mymaridae", "Nabidae",
                                                    "Noctuidae", "Notodontidae", "Orsodacnidae", "Passalidae",
                                                    "Psocidae", "Psyllidae", "Ptilodactylidae", 
                                                    "Ptinidae", "Pyralididae", "Pyralidae", "Saldidae",
                                                    "Scutelleridae", "Scydmaenidae", "Silphidae", "Sphecidae",
                                                    "Staphylinidae", "Stenotrachelidae", "Tenthredinidae",
                                                    "Vespidae") ~ "terrestrial",
                                 prey_order %in% c("Basommatophora", "Rhabdocoela",
                                                   "Cycloneritida",
                                                   "Trombidiformes",
                                                   "Aconchulinida") ~ "aquatic or terrestrial",
                                 prey_phylum %in% c("Acanthocephala") ~ "aquatic or terrestrial",
                                 prey_family %in% c("Acholeplasmataceae", "Elmidae", "Agnaridae",
                                                    "Encyrtidae", "Muscidae", "Psychodidae",
                                                    "Tipulidae", "Rhagionidae", "Scathophagidae",
                                                    "Stratiomyidae", "Syrphidae") ~ "aquatic or terrestrial",
                                 prey_class %in% c("Cestoda", "Aves", "Trepaxonemata", "Sordariomycetes",
                                                   "Arachnida","Collembola", "Trebouxiophyceae",
                                                   "Clitellata","Gammaproteobacteria",
                                                   "Gordioida", "Gastropoda", "Psychodidae") ~ "aquatic or terrestrial"))
  

temp %>% distinct(prey_origin, prey_species, prey_taxon, prey_family, prey_order, prey_class, prey_subclass, prey_superclass, prey_phylum, 
                  prey_kingdom, author, year, table_figure, prey_stage) %>% 
  arrange(prey_family) %>%
  filter(is.na(prey_origin),
         !is.na(prey_family),
         prey_family != "unknown") %>% View()

temp %>% distinct(prey_origin, prey_class) %>% filter(!is.na(prey_origin)) %>% filter(prey_class == "Gastropoda")
